autoregression: False

model:
  _target_: lib.models.SHAS
  wav2vec_model_name: facebook/wav2vec2-xls-r-300m
  wav2vec_keep_layers: 15
  finetune_wav2vec: False
  wav2vec_ft_layers: 99
  finetune_w2v_feat_enc: False
  finetune_w2v_ffn: False
  ffn_adapter: True
  n_transformer_enc_layers: 1
  n_transformer_enc_heads: 8
  init_dropout: 0.1

train_generator:
  _target_: lib.dataset.RandomDataloaderGenerator

eval_generator:
  _target_: lib.dataset.FixedDataloaderGenerator
  inference_times: 1

vocab:

loss:
  _target_: torch.nn.BCEWithLogitsLoss
  tag: bce
  pos_weight:
  ma_window:
  reduction: none
